[env]
TERM = "xterm-256color"

[window]
dimensions = {columns = 150, lines = 48}
position = { x = 245, y = 160 }
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity = 0.8
blur = true 

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
normal.style = "Regular"
bold.family = "MesloLGS Nerd Font"
bold.style = "Bold"

size = 13
offset = {x = 1, y = 1}
