[env]
TERM = "xterm-256color"

[window]
dimensions = {columns = 150, lines = 48}
position = { x = 240, y = 155 }
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
normal.style = "Regular"
bold.family = "MesloLGS Nerd Font"
bold.style = "Bold"

size = 13
offset = {x = 1, y = 1}
